search autocomplete in js
WorksHub/client pull request #46
Opened 2020-11-16 23:43 UTC by fctorial

Closes #44 . 

Note: I had to install 'react-modal' in order to start working on the master branch. 'npm run dev'  would fail without it.

2020-11-16 23:44 UTC, fctorial commented
The new file `ac.js` contains some variables that can be used for tweaking.

2020-11-17 07:37 UTC, jonki reviewed
Looks good. I've added few little comments, I'd appreciate if you could address them. I need to discuss your solution with my colleagues, but at first glance seems pretty solid and fulfilling our requirements. Thanks so much!

2020-11-17 07:37 UTC, jonki commented on client/src-js/ac.js
> +  console.log(e.key)
Probably not required anymore ;)

2020-11-17 07:37 UTC, jonki commented on client/src-js/ac.js
> +
appreciate creating this config

2020-11-17 07:37 UTC, jonki commented on client/src-js/ac.js
> +    return JSON.parse(localStorage.getItem(DB_ID))
You need something like `return JSON.parse(localStorage.getItem(DB_ID)) || []` to guard this function from returning `null` before any history is saved in storage

2020-11-17 07:37 UTC, jonki commented on client/src-js/ac.js
> +  const ip = e.target
Not sure why you call event target `ip`? Is it supposed to be `input`? If that's the case I would simply use `input`. Also relevant in other event handlers

2020-11-20 15:14 UTC, yanisurbis commented
Hello, really impressive work!

One last thing before me merge this PR :)

I see that a lot of css values are copied. May we use classes instead? It's true that css modules prefix all classes.
There is a way to create unprefixed classes though.

![image](https://user-images.githubusercontent.com/9294910/99815057-e1c88d00-2b5a-11eb-82c5-fdf270b55ec9.png)

This code will generate 3 classes which work inside our navbar
![image](https://user-images.githubusercontent.com/9294910/99815328-2f44fa00-2b5b-11eb-8d2d-8ee272361d2d.png)

So you are able to reuse them in your code without copying all css values in your code
![image](https://user-images.githubusercontent.com/9294910/99815816-e04b9480-2b5b-11eb-9590-6ccb7df3d216.png)

2020-11-20 15:17 UTC, yanisurbis requested changes

2020-11-20 15:17 UTC, yanisurbis commented on client/src-js/ac.js
> +const HOVER_COLOR = '#f4ada4'
1

2020-11-24 12:49 UTC, acron0 approved these changes

2020-11-24 12:49 UTC, acron0 commented
OK TO MERGE

2020-11-24 12:50 UTC, acron0 commented
@fctorial Can you send me an email antony@functionalworks.com please, thanks :)

2020-11-24 12:55 UTC, acron0 commented
OK TO MERGE

2020-11-24 13:00 UTC, acron0 commented
OK TO MERGE

2020-11-24 14:17 UTC, acron0 commented
This was merged upstream in https://github.com/WorksHub/works-hub/pull/3037

2020-11-24 14:17 UTC, closed without merging